export const SHOW_FILTER_ACCESSIBLE = 0
export const SHOW_FILTER_BENEFITS = 1
export const SHOW_FILTER_COMMUTE = 2
export const SHOW_FILTER_COMPANY = 3
export const SHOW_FILTER_COMPANY_SIZE = 4
export const SHOW_FILTER_DRESS_CODE = 5
export const SHOW_FILTER_EDUCATION_REQUIRED = 6
export const SHOW_FILTER_EMPLOYEE_TYPE = 7
export const SHOW_FILTER_EXPERIENCE_LEVEL = 8
export const SHOW_FILTER_INDUSTRY = 9
export const SHOW_FILTER_INTERNAL_EXTERNAL = 10
export const SHOW_FILTER_METHODOLOGY = 11
export const SHOW_FILTER_MOBILE = 12
export const SHOW_FILTER_PAYMENT = 13
export const SHOW_FILTER_PETS_ALLOWED = 14
export const SHOW_FILTER_SKILL = 15
export const SHOW_FILTER_WORKING_FROM_HOME = 16

export const SHOW_MENU = 20
export const SHOW_RESULTS = 30
export const SHOW_ACTIVE_FILTERS = 40

export const SHOW_FILTER_FIRST = SHOW_FILTER_ACCESSIBLE
export const SHOW_FILTER_LAST = SHOW_FILTER_WORKING_FROM_HOME
